<?xml version="1.0" encoding="UTF-8"?>
<!--
  opinion.xsl — client-side stylesheet for courts/ussc/opinions/xml/**/*.xml
  (generated by scripts/update_opinions.js). Every opinion XML file carries an
  <?xml-stylesheet?> PI pointing here, so browsers render it directly as a
  simple standalone reading view — no server involved. <p>/<h1>/<h2>/<h4>
  pass through with classes for hooks; <n> (a page-break marker) and <f> (a
  footnote) don't exist in HTML, so they're transformed into classed <p>s.
  The one bit of JS (a postMessage listener in <head>) exists purely so the
  doc viewer's back/forward buttons can navigate this page's own history
  reliably when it's framed cross-origin — see the listener for why.
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" encoding="UTF-8" indent="no" doctype-system="about:legacy-compat"/>

  <xsl:template match="/case">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>
          <xsl:value-of select="@title"/>
          <xsl:if test="@citation"> — <xsl:value-of select="@citation"/></xsl:if>
        </title>
        <style>
          * { box-sizing: border-box; }
          :root {
            color-scheme: light dark;
            --bg: #f6f1e7;
            --panel: rgba(255, 252, 247, 0.94);
            --ink: #1f1a17;
            --muted: #6f6258;
            --line: #d9cdbd;
            --accent: #8f3d1f;
          }
          @media (prefers-color-scheme: dark) {
            :root {
              --bg: #1b1712;
              --panel: rgba(30, 26, 22, 0.94);
              --ink: #ece4d8;
              --muted: #a89c8c;
              --line: #45392c;
              --accent: #e0a370;
            }
          }
          html, body { margin: 0; padding: 0; }
          body {
            background:
              radial-gradient(circle at top left, rgba(143, 61, 31, 0.08), transparent 28%),
              linear-gradient(180deg, color-mix(in srgb, var(--bg) 85%, white 15%), var(--bg));
            color: var(--ink);
            font-family: Iowan Old Style, Palatino Linotype, Book Antiqua, Georgia, serif;
            line-height: 1.65;
          }
          .op-page-wrap {
            max-width: 46rem;
            margin: 0 auto;
            padding: 28px 24px 72px;
          }
          .op-header {
            padding-bottom: 16px;
            margin-bottom: 24px;
            border-bottom: 1px solid var(--line);
          }
          .op-title {
            margin: 0 0 4px;
            font-size: clamp(1.4rem, 3.6vw, 1.9rem);
            line-height: 1.25;
          }
          .op-citation {
            margin: 0;
            color: var(--muted);
            font-size: 0.95rem;
          }
          .op-opinion { margin-bottom: 40px; }
          .op-opinion + .op-opinion {
            padding-top: 28px;
            border-top: 1px solid var(--line);
          }
          .op-kicker {
            margin: 0 0 14px;
            font-size: 0.75rem;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.1em;
            color: var(--accent);
          }
          h1.op-heading, h2.op-heading, h4.op-heading {
            line-height: 1.3;
            letter-spacing: 0.01em;
            margin: 1.1em 0 0.5em;
          }
          h1.op-heading { font-size: 1.3rem; }
          h2.op-heading { font-size: 1.05rem; }
          h4.op-heading {
            font-size: 0.92rem;
            font-style: italic;
            font-weight: normal;
            color: var(--muted);
          }
          p.op-p {
            margin: 0 0 1em;
            text-align: justify;
            hyphens: auto;
          }
          p.op-page {
            margin: 1.4em 0;
            text-align: center;
            font-size: 0.75rem;
            font-variant: small-caps;
            letter-spacing: 0.08em;
            color: var(--muted);
          }
          p.op-page::before, p.op-page::after {
            content: "";
            display: inline-block;
            width: 2.5em;
            border-top: 1px solid var(--line);
            vertical-align: middle;
            margin: 0 0.6em;
          }
          .op-notes-heading {
            margin-top: 2em;
            padding-top: 14px;
            border-top: 1px solid var(--line);
          }
          .op-notes { font-size: 0.85rem; color: var(--muted); }
          p.op-footnote {
            margin: 0 0 0.7em;
            text-align: left;
          }
          p.op-footnote-cont { margin-left: 1.4em; }
          p.op-footnote a:first-child {
            font-weight: 700;
            color: var(--accent);
            text-decoration: none;
            margin-right: 0.4em;
          }
          a { color: var(--accent); }
          a:hover { text-decoration-thickness: 2px; }
        </style>
        <script>
          // When this page is embedded in the doc viewer's iframe, the
          // parent app (a different origin — see OPINIONS_BASE_URL) can't
          // reliably call history.back()/forward() on a cross-origin
          // contentWindow itself — browsers don't consistently honor that,
          // even though it's technically cross-origin-accessible per spec.
          // Sidestep it entirely: the parent posts a request here instead,
          // and this page navigates its own (always-unrestricted) history.
          window.addEventListener('message', function (e) {
            if (!e.data || e.data.type !== 'ussc-doc-nav') return;
            if (e.data.dir === 'back') history.back();
            else if (e.data.dir === 'forward') history.forward();
          });
        </script>
      </head>
      <body>
        <div class="op-page-wrap">
          <header class="op-header">
            <h1 class="op-title"><xsl:value-of select="@title"/></h1>
            <xsl:if test="@citation">
              <p class="op-citation"><xsl:value-of select="@citation"/></p>
            </xsl:if>
          </header>
          <main>
            <xsl:apply-templates select="opinion"/>
          </main>
        </div>
      </body>
    </html>
  </xsl:template>

  <xsl:template match="opinion">
    <article class="op-opinion">
      <p class="op-kicker">
        <xsl:value-of select="@type"/>
        <xsl:if test="@author"><xsl:text> — </xsl:text><xsl:value-of select="@author"/></xsl:if>
      </p>
      <xsl:apply-templates select="*[not(self::f)]"/>
      <xsl:if test="f">
        <h2 class="op-heading op-notes-heading">Notes</h2>
        <div class="op-notes">
          <xsl:apply-templates select="f"/>
        </div>
      </xsl:if>
    </article>
  </xsl:template>

  <xsl:template match="h1|h2|h4">
    <xsl:element name="{name()}">
      <xsl:attribute name="class">op-heading</xsl:attribute>
      <xsl:apply-templates select="node()"/>
    </xsl:element>
  </xsl:template>

  <xsl:template match="p">
    <p class="op-p"><xsl:apply-templates select="node()"/></p>
  </xsl:template>

  <xsl:template match="n">
    <p class="op-page">
      <xsl:if test="@id"><xsl:attribute name="id"><xsl:value-of select="@id"/></xsl:attribute></xsl:if>
      <xsl:text>Page </xsl:text><xsl:apply-templates select="node()"/>
    </p>
  </xsl:template>

  <!-- A footnote is an <a> (the def marker) followed by either loose inline
       content (modern format: one paragraph) or one-or-more <p> children
       (older format: can span several paragraphs) — see update_opinions.js. -->
  <xsl:template match="f">
    <p class="op-footnote">
      <xsl:apply-templates select="a[1]"/>
      <xsl:choose>
        <xsl:when test="p">
          <xsl:text> </xsl:text>
          <xsl:apply-templates select="p[1]/node()"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:apply-templates select="node()[not(self::a)]"/>
        </xsl:otherwise>
      </xsl:choose>
    </p>
    <xsl:apply-templates select="p[position() &gt; 1]" mode="footnote-continued"/>
  </xsl:template>

  <xsl:template match="p" mode="footnote-continued">
    <p class="op-footnote op-footnote-cont"><xsl:apply-templates select="node()"/></p>
  </xsl:template>

  <xsl:template match="a">
    <a href="{@href}">
      <xsl:if test="@id"><xsl:attribute name="id"><xsl:value-of select="@id"/></xsl:attribute></xsl:if>
      <xsl:if test="starts-with(@href, 'http')">
        <xsl:attribute name="target">_blank</xsl:attribute>
        <xsl:attribute name="rel">noopener</xsl:attribute>
      </xsl:if>
      <xsl:apply-templates select="node()"/>
    </a>
  </xsl:template>

</xsl:stylesheet>
