<?xml version="1.0" encoding="UTF-8"?>
<!--
  podcast.xsl — client-side stylesheet for courts/ussc/feeds/**/*.xml
  (generated by scripts/update_cases.js's "feeds" task). Every generated feed
  carries an <?xml-stylesheet?> PI pointing here, so browsers render it as a
  simple episode-list / "how to subscribe" page instead of raw XML, no
  server or JS involved. See assets/xsl/opinion.xsl for the sibling
  opinion-viewer stylesheet this borrows its look from.
-->
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"
    xmlns:atom="http://www.w3.org/2005/Atom">
  <xsl:output method="html" encoding="UTF-8" indent="no" doctype-system="about:legacy-compat"/>

  <xsl:template match="/rss">
    <xsl:variable name="ch" select="channel"/>
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title><xsl:value-of select="$ch/title"/></title>
        <style>
          * { box-sizing: border-box; }
          :root {
            color-scheme: light dark;
            --bg: #f6f1e7;
            --panel: rgba(255, 252, 247, 0.94);
            --ink: #1f1a17;
            --muted: #6f6258;
            --line: #d9cdbd;
            --accent: #8f3d1f;
          }
          @media (prefers-color-scheme: dark) {
            :root {
              --bg: #1b1712;
              --panel: rgba(30, 26, 22, 0.94);
              --ink: #ece4d8;
              --muted: #a89c8c;
              --line: #45392c;
              --accent: #e0a370;
            }
          }
          html, body { margin: 0; padding: 0; }
          body {
            background:
              radial-gradient(circle at top left, rgba(143, 61, 31, 0.08), transparent 28%),
              linear-gradient(180deg, color-mix(in srgb, var(--bg) 85%, white 15%), var(--bg));
            color: var(--ink);
            font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif;
            line-height: 1.55;
          }
          .pod-wrap { max-width: 46rem; margin: 0 auto; padding: 28px 24px 72px; }
          .pod-header {
            display: flex;
            gap: 18px;
            align-items: flex-start;
            padding-bottom: 20px;
            margin-bottom: 24px;
            border-bottom: 1px solid var(--line);
          }
          .pod-art {
            width: 96px;
            height: 96px;
            border-radius: 14px;
            flex: none;
            object-fit: cover;
            border: 1px solid var(--line);
            background: var(--panel);
          }
          .pod-title {
            margin: 0 0 6px;
            font-size: clamp(1.3rem, 3.4vw, 1.7rem);
            line-height: 1.25;
            font-family: Iowan Old Style, Palatino Linotype, Book Antiqua, Georgia, serif;
          }
          .pod-desc { margin: 0 0 10px; color: var(--muted); font-size: 0.95rem; }
          .pod-meta { margin: 0; font-size: 0.8rem; color: var(--muted); }
          .pod-subscribe {
            margin: 0 0 28px;
            padding: 14px 16px;
            border: 1px solid var(--line);
            border-radius: 10px;
            background: var(--panel);
          }
          .pod-subscribe p { margin: 0 0 8px; font-size: 0.85rem; color: var(--muted); }
          .pod-feed-url {
            display: block;
            width: 100%;
            font: 0.85rem/1.4 ui-monospace, SFMono-Regular, Menlo, monospace;
            padding: 8px 10px;
            border-radius: 6px;
            border: 1px solid var(--line);
            background: color-mix(in srgb, var(--panel) 90%, var(--accent) 10%);
            color: var(--ink);
            overflow-wrap: anywhere;
          }
          .pod-episode {
            padding: 16px 0;
            border-top: 1px solid var(--line);
          }
          .pod-episode:first-of-type { border-top: none; }
          .pod-ep-kicker {
            margin: 0 0 4px;
            font-size: 0.72rem;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            color: var(--accent);
          }
          .pod-ep-title {
            margin: 0 0 6px;
            font-size: 1.02rem;
            line-height: 1.35;
          }
          .pod-ep-title a { color: var(--ink); text-decoration: none; }
          .pod-ep-title a:hover { text-decoration: underline; }
          .pod-ep-desc { margin: 0 0 10px; font-size: 0.88rem; color: var(--muted); }
          audio { width: 100%; height: 34px; }
          a { color: var(--accent); }
        </style>
      </head>
      <body>
        <div class="pod-wrap">
          <header class="pod-header">
            <xsl:if test="$ch/itunes:image/@href or $ch/image/url">
              <img class="pod-art" alt="">
                <xsl:attribute name="src">
                  <xsl:choose>
                    <xsl:when test="$ch/itunes:image/@href"><xsl:value-of select="$ch/itunes:image/@href"/></xsl:when>
                    <xsl:otherwise><xsl:value-of select="$ch/image/url"/></xsl:otherwise>
                  </xsl:choose>
                </xsl:attribute>
              </img>
            </xsl:if>
            <div>
              <h1 class="pod-title"><xsl:value-of select="$ch/title"/></h1>
              <p class="pod-desc"><xsl:value-of select="$ch/description"/></p>
              <p class="pod-meta">
                <xsl:value-of select="count($ch/item)"/> episode<xsl:if test="count($ch/item) != 1">s</xsl:if>
                <xsl:if test="$ch/link"> — <a href="{$ch/link}">view on the site</a></xsl:if>
              </p>
            </div>
          </header>

          <div class="pod-subscribe">
            <p>Paste this feed URL into a podcast app (Apple Podcasts, Overcast, Pocket Casts, Spotify, etc.) to subscribe:</p>
            <code class="pod-feed-url"><xsl:value-of select="$ch/atom:link[@rel='self']/@href"/></code>
          </div>

          <main>
            <xsl:apply-templates select="$ch/item"/>
          </main>
        </div>
      </body>
    </html>
  </xsl:template>

  <xsl:template match="item">
    <article class="pod-episode">
      <p class="pod-ep-kicker">
        <xsl:if test="itunes:season">Season <xsl:value-of select="itunes:season"/><xsl:text> </xsl:text></xsl:if>
        <xsl:if test="itunes:episode">Episode <xsl:value-of select="itunes:episode"/><xsl:text> — </xsl:text></xsl:if>
        <xsl:value-of select="substring(pubDate, 1, 16)"/>
      </p>
      <h2 class="pod-ep-title">
        <xsl:choose>
          <xsl:when test="link"><a href="{link}"><xsl:value-of select="title"/></a></xsl:when>
          <xsl:otherwise><xsl:value-of select="title"/></xsl:otherwise>
        </xsl:choose>
      </h2>
      <p class="pod-ep-desc">
        <xsl:value-of select="description"/>
        <xsl:if test="itunes:duration"> (<xsl:value-of select="itunes:duration"/>)</xsl:if>
      </p>
      <audio controls="controls" preload="none">
        <xsl:attribute name="src"><xsl:value-of select="enclosure/@url"/></xsl:attribute>
      </audio>
    </article>
  </xsl:template>

</xsl:stylesheet>
