title: Argument Aloud
data_dir: data
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
exclude:
  - .history
  - Gemfile
  - Gemfile.lock
  - README.md
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/default.jpg
