#!/usr/bin/env python3
"""Search journal text files for full advocate names from one-word entries.

Reads from stdin the verbose output of update_advocates.py:

    python3 scripts/update_advocates.py --verbose | python3 scripts/scrape_journals.py

For each one-word advocate name and its term/case pairs, searches
courts/ussc/journals/text/{YYYY}.txt for the case block and extracts
full advocate names from argument attribution text near the case number.

The one-word name in our data may be wrong; this script prints ALL names
found near the case number so the correct attribution can be determined.
Optionally prompts to replace the single-word name in transcript files.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JOURNALS_DIR = ROOT / "courts" / "ussc" / "journals" / "text"
SINGLES_FILE = ROOT / "scripts" / "singles.txt"

# Any hyphen/dash variant used in case numbers (hyphen, figure, en, em dash)
_DASH = r'[-\u2012\u2013\u2014]'

# Title prefixes that introduce advocate names in journal text
_TITLE = r'(?:Mr\.|Ms\.|Mrs\.|Miss)\s+(?:(?:Solicitor|Deputy)\s+(?:General|Solicitor)\s+)?'

# Name pattern: 1–5 title-case words, last word without a trailing period
# Handles "Josef Diamond", "Kenneth R. Carr", "A. William Lucas", etc.
_NAME_RE = re.compile(
    r'(?:Mr\.|Ms\.|Mrs\.|Miss)\s+(?:(?:Solicitor|Deputy)\s+(?:General|Solicitor)\s+)?'
    r'((?:[A-Z][A-Za-z.\-]*\s+){0,4}[A-Z][A-Za-z\-]+)'
    r'(?=\s+(?:for\b|and\b)|\s*[,.)\n]|\s*$)',
    re.MULTILINE,
)


# ---------------------------------------------------------------------------
# Input parsing
# ---------------------------------------------------------------------------

def parse_file() -> list[tuple[str, list[str]]]:
    """Parse singles.txt generated by update_advocates.py --singles.

    Returns list of (ONE_WORD_NAME, ['YYYY-MM/case-num', ...]) tuples.
    """
    if not SINGLES_FILE.exists():
        print(f"singles.txt not found: {SINGLES_FILE}", file=sys.stderr)
        print("Run: python3 scripts/update_advocates.py --singles", file=sys.stderr)
        sys.exit(1)
    entries: list[tuple[str, list[str]]] = []
    in_block = False
    for raw in SINGLES_FILE.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip('\n')
        if re.search(r'one-word advocate name', line):
            in_block = True
            continue
        if not in_block:
            continue
        if not line.startswith('  '):
            in_block = False
            continue
        m = re.match(r'  ([A-Z]+)(?:\s+\[[^\]]*\])*:\s+(.+)$', line)
        if not m:
            continue
        name = m.group(1)
        cases = [c.strip() for c in m.group(2).split(';') if c.strip()]
        entries.append((name, cases))
    return entries


# ---------------------------------------------------------------------------
# Journal searching
# ---------------------------------------------------------------------------

def _case_num_regex(num: str) -> re.Pattern:
    """Return a pattern matching 'No(s). ... NUM' with any dash variant."""
    # Normalise the case number's own hyphen so we can search for any dash variant
    parts = re.split(r'-', num, maxsplit=1)
    if len(parts) == 2:
        pat = rf'{re.escape(parts[0])}{_DASH}{re.escape(parts[1])}'
    else:
        pat = re.escape(num)
    # Require "No." at the start of a line (case entry), allow other numbers
    # before ours (e.g. "Nos. 73-100, 73-235").  \b on both sides ensures
    # "53" doesn't match "153" or "532".  Negative lookahead excludes
    # misc-docket entries like "No. 53, Misc."
    return re.compile(
        rf'^No[s]?\.(?:[^\n]{{0,80}}?)\b{pat}\b(?!,\s*Misc)',
        re.IGNORECASE | re.MULTILINE,
    )


def find_case_blocks(text: str, case_num: str, window: int = 800) -> list[str]:
    """Return all journal text blocks for case_num (may appear many times)."""
    pat = _case_num_regex(case_num)
    blocks: list[str] = []
    for m in pat.finditer(text):
        start = m.start()
        tail = text[start + 5:]  # skip past current "No."
        # End at the first of: next case entry, blank line, session boundary, or window
        nxt = re.search(r'\nNo[s]?\.\s|\n\n|\nAdjourned|\nPresent:', tail)
        end = start + 5 + (nxt.start() if nxt else window)
        block = text[start:end]
        # Normalize soft line-wraps:
        #   "word-\nnext"  →  "word-next"  (hyphenated breaks)
        block = re.sub(r'-\n', '-', block)
        #   line starting with lowercase/comma is a continuation
        block = re.sub(r'\n(?=[a-z,])', ' ', block)
        blocks.append(block)
    return blocks


def extract_names(block: str) -> list[str]:
    """Return ALL-CAPS advocate names extracted from a journal case block.

    Filters out justice names (Chief Justice X, Justice X) which appear in
    opinion-announcement text within the same case entry.
    """
    names: list[str] = []
    for m in _NAME_RE.finditer(block):
        name = ' '.join(m.group(1).split())  # collapse all whitespace incl. newlines
        words = name.upper().split()
        # Require at least two words
        if len(words) < 2:
            continue
        # Skip "Chief Justice X", "Justice X", "Associate Justice X"
        if words[0] in ('JUSTICE', 'CHIEF', 'ASSOCIATE'):
            continue
        if len(words) >= 2 and words[1] == 'JUSTICE':
            continue
        names.append(name.upper())
    return list(dict.fromkeys(names))  # deduplicate, preserve order


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

TERMS_DIR = ROOT / "courts" / "ussc" / "terms"


def _case_folder(case_num: str) -> str:
    """Return folder name for a case number (consolidated 'A,B' -> 'A')."""
    return case_num.split(",")[0].strip()


def _levenshtein(a: str, b: str) -> int:
    """Return the edit distance between two strings."""
    if a == b:
        return 0
    if len(a) < len(b):
        a, b = b, a
    if not b:
        return len(a)
    prev = list(range(len(b) + 1))
    for ca in a:
        curr = [prev[0] + 1]
        for j, cb in enumerate(b, 1):
            curr.append(min(prev[j] + 1, curr[j - 1] + 1, prev[j - 1] + (ca != cb)))
        prev = curr
    return prev[-1]


def _journal_match(journal_name: str, transcript_last: str) -> str | None:
    """Return the name to offer as a replacement, or None if no match.

    Three match strategies (all case-sensitive on the last word, which is
    already upper-cased by extract_names):
      1. Exact last-word match  → journal_name unchanged
      2. Dehyphenated match: last word with hyphens removed == transcript_last
         → return journal_name with last word replaced by transcript_last
      3. Edit-distance-1 match  → journal_name unchanged (OCR/typo tolerance)

    In all cases, hyphens in non-last words (OCR line-break artifacts in
    first/middle names, e.g. "ROB-ERT") are removed before returning.
    """
    words = journal_name.split()
    last = words[-1]

    if last == transcript_last:
        offered_words = words
    elif last.replace('-', '') == transcript_last:
        offered_words = words[:-1] + [transcript_last]
    elif _levenshtein(last, transcript_last) == 1:
        offered_words = words
    else:
        return None

    # Remove OCR line-break hyphens from non-last words (e.g. "ROB-ERT" → "ROBERT")
    cleaned = [w.replace('-', '') if i < len(offered_words) - 1 else w
               for i, w in enumerate(offered_words)]
    return ' '.join(cleaned)


def _replace_in_transcripts(term: str, case_num: str, old_upper: str, full_name: str) -> int:
    """Replace all occurrences of old_upper speaker name with full_name in the case folder.

    Updates media.speakers[].name and turns[].name.
    Deduplicates speakers with identical (name, title); warns if same name but
    different title appears.  Returns the number of files modified.
    """
    folder = TERMS_DIR / term / "cases" / _case_folder(case_num)
    if not folder.is_dir():
        print(f"    (case folder not found: {folder.relative_to(ROOT)})", file=sys.stderr)
        return 0
    modified = 0
    for tpath in sorted(folder.glob("*.json")):
        try:
            data = json.loads(tpath.read_text(encoding="utf-8"))
        except Exception as exc:
            print(f"    WARNING: could not parse {tpath.name}: {exc}", file=sys.stderr)
            continue
        changed = False
        # Rename in speakers and turns
        for sp in data.get("media", {}).get("speakers", []):
            if sp.get("name", "").strip().upper() == old_upper:
                sp["name"] = full_name
                changed = True
        for turn in data.get("turns", []):
            if turn.get("name", "").strip().upper() == old_upper:
                turn["name"] = full_name
                changed = True
        # Deduplicate speakers and warn on conflicting titles
        speakers = data.get("media", {}).get("speakers", [])
        seen_key: set[tuple[str, str]] = set()
        seen_name: dict[str, str] = {}  # name_upper -> title_upper (first seen)
        deduped: list[dict] = []
        for sp in speakers:
            sp_name = sp.get("name", "").strip().upper()
            sp_title = sp.get("title", "").strip().upper()
            key = (sp_name, sp_title)
            if key in seen_key:
                changed = True  # exact duplicate removed
                continue
            seen_key.add(key)
            if sp_name in seen_name:
                if seen_name[sp_name] != sp_title:
                    print(
                        f"    WARNING: '{sp.get('name', '')}' has conflicting titles "
                        f"in {tpath}",
                        file=sys.stderr,
                    )
            else:
                seen_name[sp_name] = sp_title
            deduped.append(sp)
        if len(deduped) < len(speakers):
            data["media"]["speakers"] = deduped
        if changed:
            tpath.write_text(
                json.dumps(data, indent=2, ensure_ascii=False) + "\n",
                encoding="utf-8",
            )
            print(f"    Updated {tpath.relative_to(ROOT)}")
            modified += 1
    return modified


def main() -> None:
    entries = parse_file()
    if not entries:
        print(
            f"No one-word advocate entries found in {SINGLES_FILE.name}.\n"
            "Run: python3 scripts/update_advocates.py --singles",
            file=sys.stderr,
        )
        sys.exit(1)

    journal_cache: dict[str, str] = {}

    for name, cases in sorted(entries):
        print(f"\n{name}:")
        for term_case in sorted(cases):
            if '/' not in term_case:
                print(f"  {term_case}: (unrecognised format)")
                continue
            term, case_num = term_case.split('/', 1)
            year = term.split('-')[0]

            if year not in journal_cache:
                path = JOURNALS_DIR / f"{year}.txt"
                journal_cache[year] = (
                    path.read_text(encoding='utf-8', errors='replace')
                    if path.exists() else ''
                )

            text = journal_cache[year]
            if not text:
                print(f"  {term_case}: no journal file for {year}")
                continue

            blocks = find_case_blocks(text, case_num)
            if not blocks:
                print(f"  {term_case}: case not found in {year}.txt")
                continue

            # Collect names from all blocks (case may appear multiple times)
            all_names: list[str] = []
            for block in blocks:
                all_names.extend(extract_names(block))
            found = list(dict.fromkeys(all_names))  # deduplicate, preserve order

            if found:
                print(f"  {term_case}: {', '.join(found)}")
            else:
                # Print a snippet from each block for manual inspection
                snippets = ' | '.join(b[:150].replace('\n', ' ') for b in blocks)
                print(f"  {term_case}: no names found — {snippets!r}")
                continue

            # Build match list using exact, dehyphenated, and edit-distance-1 strategies
            matches: list[str] = []
            for n in found:
                offered = _journal_match(n, name)
                if offered and offered not in matches:
                    matches.append(offered)
            if not matches:
                continue

            # Prompt user to replace in transcripts
            if len(matches) == 1:
                full_name = matches[0]
                try:
                    raw = input(f"  Replace \"{name}\" with \"{full_name}\" in {term_case} transcripts? [y/N] ").strip().lower()
                except EOFError:
                    raw = ''
                if raw == 'y':
                    n = _replace_in_transcripts(term, case_num, name, full_name)
                    if not n:
                        print(f"    (no transcript files updated)")
            else:
                print(f"  Multiple matches for {name} in {term_case}:")
                for i, n in enumerate(matches, 1):
                    print(f"    {i}. {n}")
                try:
                    raw = input(f"  Replace \"{name}\" with which name? [1-{len(matches)}, 0=skip, default 0] ").strip()
                except EOFError:
                    raw = '0'
                if raw.isdigit() and 1 <= int(raw) <= len(matches):
                    full_name = matches[int(raw) - 1]
                    n = _replace_in_transcripts(term, case_num, name, full_name)
                    if not n:
                        print(f"    (no transcript files updated)")


if __name__ == '__main__':
    main()
